"""Initial

Revision ID: 6ffff56b673c
Revises: 
Create Date: 2025-11-18 22:06:32.483717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ffff56b673c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'FILE', 'YOUTUBE', name='materialtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_materials_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_materials'))
    )
    op.create_index(op.f('ix_lesson_materials_id'), 'lesson_materials', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_materials_lesson_id'), 'lesson_materials', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_materials_type'), 'lesson_materials', ['type'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_submissions_student_id_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_submissions_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('ai_similarity', sa.Float(), nullable=False),
    sa.Column('intra_group_similarity', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_evaluations_submission_id_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index(op.f('ix_evaluations_ai_similarity'), 'evaluations', ['ai_similarity'], unique=False)
    op.create_index(op.f('ix_evaluations_final_score'), 'evaluations', ['final_score'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_intra_group_similarity'), 'evaluations', ['intra_group_similarity'], unique=False)
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=True)
    op.drop_table('student_solutions')
    op.drop_table('comparisons')
    op.drop_table('students')
    op.drop_table('web_solutions')
    op.add_column('ai_solutions', sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', name='aiprovider'), nullable=False))
    op.add_column('ai_solutions', sa.Column('variant_index', sa.Integer(), nullable=False))
    op.add_column('ai_solutions', sa.Column('meta', sa.Text(), nullable=True))
    op.add_column('ai_solutions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('ai_solutions', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_solutions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_solutions_id'), 'ai_solutions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_solutions_provider'), 'ai_solutions', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_solutions_task_id'), 'ai_solutions', ['task_id'], unique=False)
    op.create_index(op.f('ix_ai_solutions_variant_index'), 'ai_solutions', ['variant_index'], unique=False)
    op.drop_constraint(op.f('ai_solutions_task_id_fkey'), 'ai_solutions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_solutions_task_id_tasks'), 'ai_solutions', 'tasks', ['task_id'], ['id'])
    op.drop_column('ai_solutions', 'model_name')
    op.add_column('groups', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.drop_column('groups', 'number')
    op.add_column('lessons', sa.Column('video_url', sa.String(length=1024), nullable=True))
    op.add_column('lessons', sa.Column('video_description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lessons', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_subject_id'), 'lessons', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lessons_title'), 'lessons', ['title'], unique=False)
    op.drop_constraint(op.f('lessons_subject_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lessons_subject_id_subjects'), 'lessons', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('fk_lessons_teacher_id_users'), 'lessons', 'users', ['teacher_id'], ['id'])
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('subjects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('subjects_name_key'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.drop_column('subjects', 'description')
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('tasks', sa.Column('language', sa.Enum('PYTHON', 'JAVA', 'JAVASCRIPT', 'CPP', 'C', 'CSHARP', 'GO', 'RUST', name='programminglanguage'), nullable=False))
    op.add_column('tasks', sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tasks_deadline_at'), 'tasks', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_language'), 'tasks', ['language'], unique=False)
    op.create_index(op.f('ix_tasks_lesson_id'), 'tasks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_constraint(op.f('tasks_lesson_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_lesson_id_lessons'), 'tasks', 'lessons', ['lesson_id'], ['id'])
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'name')
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'teacher', 'admin', name='user_role'),
               type_=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(op.f('fk_users_group_id_groups'), 'users', 'groups', ['group_id'], ['id'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_users_group_id_groups'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               type_=postgresql.ENUM('student', 'teacher', 'admin', name='user_role'),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.add_column('tasks', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_tasks_lesson_id_lessons'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_lesson_id_fkey'), 'tasks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_lesson_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_language'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline_at'), table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'deadline_at')
    op.drop_column('tasks', 'language')
    op.drop_column('tasks', 'body')
    op.drop_column('tasks', 'title')
    op.add_column('subjects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_name_key'), 'subjects', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'created_at')
    op.drop_constraint(op.f('fk_lessons_teacher_id_users'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('fk_lessons_subject_id_subjects'), 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_subject_id_fkey'), 'lessons', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lessons_title'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_subject_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.alter_column('lessons', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('lessons', 'updated_at')
    op.drop_column('lessons', 'teacher_id')
    op.drop_column('lessons', 'video_description')
    op.drop_column('lessons', 'video_url')
    op.add_column('groups', sa.Column('number', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'name')
    op.add_column('ai_solutions', sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_ai_solutions_task_id_tasks'), 'ai_solutions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_solutions_task_id_fkey'), 'ai_solutions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_solutions_variant_index'), table_name='ai_solutions')
    op.drop_index(op.f('ix_ai_solutions_task_id'), table_name='ai_solutions')
    op.drop_index(op.f('ix_ai_solutions_provider'), table_name='ai_solutions')
    op.drop_index(op.f('ix_ai_solutions_id'), table_name='ai_solutions')
    op.alter_column('ai_solutions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_solutions', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('ai_solutions', 'updated_at')
    op.drop_column('ai_solutions', 'meta')
    op.drop_column('ai_solutions', 'variant_index')
    op.drop_column('ai_solutions', 'provider')
    op.create_table('web_solutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('web_solutions_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('web_solutions_pkey'))
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('students_group_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('students_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('students_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('comparisons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_solution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_type', postgresql.ENUM('ai', 'web', 'student', name='user_ref_type'), autoincrement=False, nullable=True),
    sa.Column('similarity_score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('style_score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('final_label', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('final_label >= 0 AND final_label <= 100', name=op.f('comparisons_final_label_check')),
    sa.CheckConstraint('similarity_score > 0::double precision AND similarity_score <= 1::double precision', name=op.f('comparisons_similarity_score_check')),
    sa.CheckConstraint('style_score >= 0::double precision AND style_score <= 1::double precision', name=op.f('comparisons_style_score_check')),
    sa.ForeignKeyConstraint(['student_solution_id'], ['student_solutions.id'], name=op.f('comparisons_student_solution_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comparisons_pkey'))
    )
    op.create_table('student_solutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('student_solutions_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('student_solutions_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_solutions_pkey'))
    )
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_intra_group_similarity'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_final_score'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_ai_similarity'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_lesson_materials_type'), table_name='lesson_materials')
    op.drop_index(op.f('ix_lesson_materials_lesson_id'), table_name='lesson_materials')
    op.drop_index(op.f('ix_lesson_materials_id'), table_name='lesson_materials')
    op.drop_table('lesson_materials')
    # ### end Alembic commands ###

