"""add_is_public_to_task_tests

Revision ID: 775263b324ed
Revises: 646316f29793
Create Date: 2025-12-11 11:25:26.239821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '775263b324ed'
down_revision: Union[str, Sequence[str], None] = '646316f29793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_score', sa.Integer(), nullable=True),
    sa.Column('practice_score', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_journal_entries_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_journal_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_lesson_id'), 'journal_entries', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.alter_column('lesson_materials', 'use_for_ai_generation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lesson_progress', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lesson_progress', 'sections_completed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_practice_results_id'), 'practice_results', ['id'], unique=False)
    op.add_column('task_tests', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.alter_column('task_tests', 'test_type',
               existing_type=postgresql.ENUM('UNIT', 'INTEGRATION', 'CUSTOM', name='testtype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_tests', 'weight',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_tests', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_task_tests_is_public'), 'task_tests', ['is_public'], unique=False)
    op.create_index(op.f('ix_test_attempts_id'), 'test_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_test_questions_id'), 'test_questions', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_questions_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_attempts_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_task_tests_is_public'), table_name='task_tests')
    op.alter_column('task_tests', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('task_tests', 'weight',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('task_tests', 'test_type',
               existing_type=postgresql.ENUM('UNIT', 'INTEGRATION', 'CUSTOM', name='testtype'),
               server_default=sa.text("'UNIT'::testtype"),
               existing_nullable=False)
    op.drop_column('task_tests', 'is_public')
    op.drop_index(op.f('ix_practice_results_id'), table_name='practice_results')
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'sections_completed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text('\'{"video": false, "theory": false, "practice": false}\'::json'),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('lesson_materials', 'use_for_ai_generation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_lesson_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
