"""add_submission_resubmission_columns

Revision ID: af8800040578
Revises: add_order_to_lessons
Create Date: 2025-12-15 20:08:58.943942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8800040578'
down_revision: Union[str, Sequence[str], None] = 'add_order_to_lessons'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='gradingjobstatus'), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('processed_submissions', sa.Integer(), nullable=False),
    sa.Column('successful_evaluations', sa.Integer(), nullable=False),
    sa.Column('failed_evaluations', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_grading_jobs_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_grading_jobs_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_jobs'))
    )
    op.create_index(op.f('ix_grading_jobs_celery_task_id'), 'grading_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_grading_jobs_id'), 'grading_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_grading_jobs_status'), 'grading_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_grading_jobs_task_id'), 'grading_jobs', ['task_id'], unique=False)
    op.create_index(op.f('ix_grading_jobs_teacher_id'), 'grading_jobs', ['teacher_id'], unique=False)
    op.add_column('evaluations', sa.Column('test_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('test_passed', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('test_total', sa.Integer(), nullable=True))
    op.alter_column('subjects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.add_column('submissions', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('test_passed_count', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('test_total_count', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('test_score', sa.Float(), nullable=True))
    op.create_unique_constraint('uq_student_task_attempt', 'submissions', ['student_id', 'task_id', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_task_attempt', 'submissions', type_='unique')
    op.drop_column('submissions', 'test_score')
    op.drop_column('submissions', 'test_total_count')
    op.drop_column('submissions', 'test_passed_count')
    op.drop_column('submissions', 'attempt_number')
    op.alter_column('subjects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Активен'::character varying"),
               existing_nullable=True)
    op.drop_column('evaluations', 'test_total')
    op.drop_column('evaluations', 'test_passed')
    op.drop_column('evaluations', 'test_score')
    op.drop_index(op.f('ix_grading_jobs_teacher_id'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_task_id'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_status'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_id'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_celery_task_id'), table_name='grading_jobs')
    op.drop_table('grading_jobs')
    # ### end Alembic commands ###
