from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

from app.models.ai_solution import AIProvider


class AISolutionBase(BaseModel):
    """Base AISolution schema with common fields."""
    task_id: int = Field(..., description="Task ID")
    provider: AIProvider = Field(..., description="AI provider")
    variant_index: int = Field(..., ge=1, le=3, description="Solution variant number")
    code: str = Field(..., min_length=1, description="AI-generated code")
    meta: Optional[str] = Field(None, description="JSON metadata")


class AISolutionCreate(AISolutionBase):
    pass


class AISolutionRead(AISolutionBase):
    id: int = Field(..., description="AI Solution ID")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")
    
    code_length: int = Field(..., description="Length of AI-generated code")
    code_lines: int = Field(..., description="Number of lines in code")
    model_name: Optional[str] = Field(None, description="AI model name")
    prompt_used: Optional[str] = Field(None, description="Prompt used for generation")
    tokens_used: Optional[int] = Field(None, description="Tokens used for generation")
    is_openai_solution: bool = Field(..., description="Whether generated by OpenAI")
    is_anthropic_solution: bool = Field(..., description="Whether generated by Anthropic")
    
    class Config:
        from_attributes = True


class AISolutionUpdate(BaseModel):
    """Schema for updating AI solution data."""
    code: Optional[str] = Field(None, min_length=1)
    meta: Optional[str] = Field(None)


class AISolutionList(BaseModel):
    """Schema for paginated AI solution list response."""
    ai_solutions: List[AISolutionRead]
    total: int
    page: int
    size: int


class AISolutionWithTask(AISolutionRead):
    """Schema for AI solution with task details."""
    task: Optional['TaskRead'] = Field(None, description="Task details")

try:
    from app.schemas.task import TaskRead
except Exception:
    TaskRead = None

try:
    AISolutionWithTask.model_rebuild()
except Exception:
    pass


class AISolutionMetadata(BaseModel):
    """Schema for AI solution metadata."""
    model: Optional[str] = Field(None, description="AI model used")
    prompt: Optional[str] = Field(None, description="Prompt used")
    tokens: Optional[int] = Field(None, description="Tokens consumed")
    temperature: Optional[float] = Field(None, description="Generation temperature")
    max_tokens: Optional[int] = Field(None, description="Maximum tokens")
    response_time: Optional[float] = Field(None, description="Response time in seconds")


class TaskAISolutionSummary(BaseModel):
    task_id: int
    task_title: str
    total_solutions: int
    openai_solutions: int
    anthropic_solutions: int
    average_code_length: Optional[float]
    generation_status: str = Field(description="complete, partial, or pending")